# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Zip', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Person'),
        ),
    ]
