# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20160619_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('to_name', models.CharField(max_length=255)),
                ('from_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='RelationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.RelationType'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_name_set', to='frontend.Person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_name_set', to='frontend.Person'),
        ),
    ]
